# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 134996c0587e1b22c1883cf7e97d1aab04814363a394c6a83a7e97ce1c91dd3eed39d934d7ce0385546c9c8d775193255a80ac46bfb641c0e0527c22be6b057b

test:
  secret_key_base: 5769398fcd0840a82b7807e9bbfc1ddb54091114ac6d140ae247acbeabd0e1d02c9e18b45b6bd632739c9dc208bb199f0b1ae915b95c69646b284ae5b5fa3f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
